name: Buildroot ramdisk filesystem

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            dwarves \
            cpio \
            kmod \
            git \
            rsync \
            dpkg-dev \
            wget \
            xz-utils

      - name: Clone buildroot
        run: |
          git clone https://github.com/buildroot/buildroot

      - name: Configure buildroot
        run: |
          set -o pipefail
          cd buildroot
          {
            make qemu_x86_64_defconfig
            ./support/kconfig/merge_config.sh .config ../buildroot-config/ci.config

          } 2>&1 | tee -a ../mylog.txt

      - name: Make
        run: |
          set -o pipefail

          cd buildroot

          {
            make olddefconfig
            make -j$(nproc)

          } 2>&1 | tee -a ../mylog.txt

      - name: Collect artifacts
        run: |
          mkdir -p output

          cp mylog.txt output/

          cp ./buildroot/output/images/rootfs.cpio.gz 2>/dev/null || true

          echo "=== Artifact contents ==="
          ls -lh output

          tar czvf buildroot-qemu.tar.gz \
            -C output .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: buildroot-qemu
          path: buildroot-qemu.tar.gz
