name: Compile kernel2029

on:
  push:
    branches: [compile-kernel2019]
  pull_request:
    branches: [compile-kernel2019]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            dwarves \
            cpio \
            kmod \
            git \
            rsync \
            dpkg-dev \
            wget \
            xz-utils

      - name: Clone
        run: |
          wget -q https://github.com/torvalds/linux/archive/459e3a21535ae3c7a9a123650e54f5c882b8fcbf.tar.gz -O linux.tar.gz
          mkdir linux
          tar xzf linux.tar.gz -C linux --strip-components=1
          cd linux
          wget -O .config 'https://syzkaller.appspot.com/text?tag=KernelConfig&x=ef1b87b455c397cf'
          cp .config .config.syzbot

      - name: Configure kernel
        run: |
          set -o pipefail
          cd linux
          {
            make olddefconfig

          } 2>&1 | tee -a ../mylog.txt

      - name: Making kernel
        run: |
          set -o pipefail
          cd linux
          {
            make -j$(nproc)

          } 2>&1 | tee -a ../mylog.txt

      - name: Collect artifacts
        run: |
          mkdir -p output

          cp mylog.txt output/

          cp -R ./syzkaller/bin output 2>/dev/null || true
          cp -R ./syzkaller/sys output 2>/dev/null || true

          echo "=== Artifact contents ==="
          ls -lh output

          tar czvf result.tar.gz \
            -C output .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: result.tar.gz
